// Original PCM sound bank, generated by scripts/generate_audio.py.
// One gesture-unlocked mixer serves title, world and work events. No autoplay or network providers.
const VaultAudio=(()=>{
  const BANK={air:'campus-air',hum:'district-hum',footstep:'footstep',ui:'ui',notification:'notification',complete:'complete',transition:'transition'};
  const busLevel={ambient:.3,effects:.5,work:.55};
  let ctx=null,master=null,buses=null,ready=null,unlocked=false,enabled=true,disposed=false,generation=0;
  let ambientWanted=false,districtId='',lastStep=-Infinity,lastWork=-Infinity;
  const buffers=new Map(),voices=new Set(),loops=new Map();
  const readEnabled=()=>{try{return JSON.parse(localStorage.getItem('vault.sound')||'true')!==false}catch{return true}};
  const point=p=>Array.isArray(p)?p:[p?.x||0,p?.y||0,p?.z||0];
  function ramp(param,value,seconds=.2){if(!ctx)return;param.cancelScheduledValues(ctx.currentTime);param.setValueAtTime(param.value,ctx.currentTime);param.linearRampToValueAtTime(value,ctx.currentTime+seconds)}
  function init(){
    if(ctx)return true;
    const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;
    if(!Audio)return false;
    try{ctx=new Audio();disposed=false;enabled=readEnabled();master=ctx.createGain();master.gain.value=enabled?.65:0;
      const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-16;limiter.knee.value=18;limiter.ratio.value=4;
      master.connect(limiter);limiter.connect(ctx.destination);buses={};
      for(const [name,value] of Object.entries(busLevel)){const g=ctx.createGain();g.gain.value=value;g.connect(master);buses[name]=g}
      return true;
    }catch{ctx=null;return false}
  }
  async function preload(){
    if(ready)return ready;if(!init())return false;
    const audio=ctx,epoch=generation;
    ready=Promise.all(Object.entries(BANK).map(async([name,file])=>{
      try{const response=await fetch('audio/'+file+'.wav',{cache:'force-cache'});if(!response.ok)return;
        const buffer=await audio.decodeAudioData(await response.arrayBuffer());if(epoch===generation&&!disposed)buffers.set(name,buffer);
      }catch{/* A missing audio file must never block work or sign-in. */}
    })).then(()=>{if(epoch===generation&&ambientWanted)ambient(true);return epoch===generation});
    return ready;
  }
  function unlock(){if(!init())return Promise.resolve(false);unlocked=true;enabled=readEnabled();
    const resumed=ctx.state==='suspended'?ctx.resume():Promise.resolve();
    return resumed.then(()=>preload()).catch(()=>false);
  }
  function voice(name,{position=null,volume=1,loop=false,bus='effects',rate=1}={}){
    if(!ctx||!unlocked||!enabled||ctx.state!=='running'||document.hidden)return null;
    const buffer=buffers.get(name);if(!buffer)return null;
    // Keep overlapping realtime notifications bounded; ambient loops retain their voices.
    if(voices.size>=24&&!loop)return null;
    const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=loop;source.playbackRate.value=Math.max(.5,Math.min(2,rate));
    gain.gain.value=Math.max(0,Math.min(1,volume));source.connect(gain);
    let panner=null;
    if(position&&ctx.createPanner){panner=ctx.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=4;panner.maxDistance=90;panner.rolloffFactor=1;
      const [x,y,z]=point(position);if(panner.positionX){panner.positionX.value=x;panner.positionY.value=y;panner.positionZ.value=z}else panner.setPosition(x,y,z);
      gain.connect(panner);panner.connect(buses[bus]||buses.effects);
    }else gain.connect(buses[bus]||buses.effects);
    const handle={source,gain,panner,stop(){try{source.stop()}catch{}}};voices.add(handle);
    source.onended=()=>{voices.delete(handle);source.disconnect();gain.disconnect();if(panner)panner.disconnect()};
    source.start();return handle;
  }
  function play(name,options){return voice(name,options)}
  function stopLoops(){for(const handle of loops.values())handle.stop();loops.clear()}
  function ambient(on=true){ambientWanted=!!on;if(!on||!enabled||document.hidden){stopLoops();return}
    for(const [key,name,volume] of [['air','air',.65],['hum','hum',.38]])if(!loops.has(key)){const v=voice(name,{loop:true,bus:'ambient',volume});if(v)loops.set(key,v)}
  }
  function setEnabled(value){enabled=!!value;try{localStorage.setItem('vault.sound',JSON.stringify(enabled))}catch{}
    if(master)ramp(master.gain,enabled?.65:0,.1);
    if(!enabled){stopLoops();for(const v of [...voices])v.stop()}else{unlock();if(ambientWanted)ambient()}
  }
  function listener(position,forward=[0,0,-1]){
    if(!ctx)return;const l=ctx.listener,[x,y,z]=point(position),[fx,fy,fz]=point(forward);
    if(l.positionX){l.positionX.value=x;l.positionY.value=y;l.positionZ.value=z;l.forwardX.value=fx;l.forwardY.value=fy;l.forwardZ.value=fz;l.upX.value=0;l.upY.value=1;l.upZ.value=0}
    else{l.setPosition(x,y,z);l.setOrientation(fx,fy,fz,0,1,0)}
  }
  function footstep(position,speed=1){const now=globalThis.performance?.now()||Date.now();if(now-lastStep<Math.max(180,460/Math.max(.5,speed)))return;lastStep=now;return play('footstep',{position,volume:.38,rate:.95+(lastStep%7)*.01})}
  function district(id){if(id===districtId)return;districtId=id;const key=[...String(id)].reduce((n,c)=>n+c.charCodeAt(0),0);const hum=loops.get('hum');if(hum)ramp(hum.source.playbackRate,.92+(key%9)*.02,1.6);play('transition',{volume:.16})}
  function workEvent(kind,position){const name= /done|complete|level/.test(kind)?'complete':/say|message|write|append|task/.test(kind)?'notification':'ui';
    const now=globalThis.performance?.now()||Date.now();if(now-lastWork<350)return;lastWork=now;play(name,{bus:'work',position,volume:.6})}
  function visibility(){if(document.hidden){stopLoops();if(ctx)ctx.suspend().catch(()=>{})}else if(ctx&&unlocked){ctx.resume().then(()=>{if(ambientWanted)ambient()}).catch(()=>{})}}
  if(typeof document!=='undefined')document.addEventListener('visibilitychange',visibility);
  async function dispose(){disposed=true;generation++;ambientWanted=false;stopLoops();for(const v of [...voices])v.stop();buffers.clear();ready=null;unlocked=false;
    const audio=ctx;ctx=null;master=null;buses=null;if(audio)await audio.close().catch(()=>{});
  }
  return{unlock,preload,play,ambient,setEnabled,listener,footstep,district,workEvent,dispose,status:()=>({unlocked,enabled,loaded:buffers.size,voices:voices.size,district:districtId})};
})();
