// Actual production character factory, lit in a repeatable six-person contact sheet.
import {chromium} from 'playwright';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(new URL('../',import.meta.url).pathname),out=path.join(root,'docs/visual-quality-evidence');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=req.url.split('?')[0];if(p==='/'){res.setHeader('content-type','text/html');res.end('<meta charset="utf-8"><body style="margin:0;background:#282e32"><script src="/web/vendor/three-r128.min.js"></script><script src="/web-src/b_identity.js"></script><script src="/web-src/b_sentinel.js"></script></body>');return}if(p.startsWith('/assets/'))p='/web'+p;try{res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(path.join(root,p)))}catch{res.statusCode=404;res.end()}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:2100,height:1500},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://127.0.0.1:'+server.address().port);
const stats=await page.evaluate(async()=>{
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(2100,1500);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.appendChild(renderer.domElement);SentinelMesh.environment(renderer);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#353d43');const camera=new THREE.PerspectiveCamera(31,700/750,.1,120);camera.position.set(6,4.9,12.8);camera.lookAt(0,3.1,0);
 scene.add(new THREE.HemisphereLight('#e8f3ff','#756247',.7));const key=new THREE.DirectionalLight('#fff0d5',2.3);key.position.set(-7,14,12);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-15;key.shadow.camera.right=15;key.shadow.camera.top=10;key.shadow.camera.bottom=-10;scene.add(key);const fill=new THREE.DirectionalLight('#a4d5ff',.8);fill.position.set(9,7,-7);scene.add(fill);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#444b4b',roughness:.98}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 const forms=['jr','devon','ahmad','kenza','member','agent'],stats=[],models=[];
 for(let i=0;i<6;i++){const f=forms[i],m=SentinelMesh.create({id:'proof-'+f,form:f,palette:Identity.FORMS[f].palette,level:10});scene.add(m.grp);SentinelMesh.pose(m,2,'idle');m.ring.visible=false;m.aura.visible=false;m.grp.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});stats.push({form:f,...SentinelMesh.stats(m)});models.push(m);m.grp.visible=false;
 const label=document.createElement('div');label.textContent=Identity.FORMS[f].name;Object.assign(label.style,{position:'absolute',left:((i%3)*700+25)+'px',top:(Math.floor(i/3)*750+20)+'px',font:'22px sans-serif',color:'#f4f0e5',letterSpacing:'2px'});document.body.appendChild(label)}
 await new Promise(r=>setTimeout(r,1800));renderer.setScissorTest(true);
 for(let i=0;i<6;i++){renderer.setViewport(i%3*700,(1-Math.floor(i/3))*750,700,750);renderer.setScissor(i%3*700,(1-Math.floor(i/3))*750,700,750);models[i].grp.visible=true;renderer.render(scene,camera);models[i].grp.visible=false}return stats;
});await page.screenshot({path:path.join(out,'sentinels.jpg'),quality:94});fs.writeFileSync(path.join(out,'sentinels.json'),JSON.stringify({stats,errors},null,2));if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({file:path.join(out,'sentinels.jpg'),figures:stats.length}));
}finally{await browser.close();server.close()}
